-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/4/5 16:22:49
-- Server version: 5.6.28-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE jsuweb;

--
-- Definition for table sys_menu_info
--
DROP TABLE IF EXISTS sys_menu_info;
CREATE TABLE sys_menu_info (
  menu_id VARCHAR(20) NOT NULL COMMENT '编号',
  menu_name VARCHAR(80) DEFAULT NULL COMMENT '菜单名称',
  menu_order VARCHAR(20) DEFAULT NULL COMMENT '排序',
  link_url VARCHAR(768) DEFAULT NULL COMMENT '连接地址',
  disp_image VARCHAR(192) DEFAULT NULL COMMENT '显示图标',
  status CHAR(1) DEFAULT '1' COMMENT '状态，0禁用，1正常',
  remark VARCHAR(100) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (menu_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 309
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统菜单信息表';

--
-- Definition for table sys_role_info
--
DROP TABLE IF EXISTS sys_role_info;
CREATE TABLE sys_role_info (
  role_id VARCHAR(20) NOT NULL COMMENT 'id',
  role_name VARCHAR(32) DEFAULT NULL COMMENT '角色名称',
  create_user INT(11) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  remark VARCHAR(100) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (role_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统角色信息表';

--
-- Definition for table sys_seq
--
DROP TABLE IF EXISTS sys_seq;
CREATE TABLE sys_seq (
  name VARCHAR(50) NOT NULL COMMENT '标识名称',
  val BIGINT(32) UNSIGNED NOT NULL COMMENT '值',
  raise INT(10) UNSIGNED NOT NULL DEFAULT 1 COMMENT '增加数',
  `desc` VARCHAR(128) DEFAULT NULL COMMENT '描述',
  PRIMARY KEY (name)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '主键生成记录表';

--
-- Definition for table sys_user_info
--
DROP TABLE IF EXISTS sys_user_info;
CREATE TABLE sys_user_info (
  user_id INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  login_name VARCHAR(32) DEFAULT NULL COMMENT '登录名',
  name VARCHAR(32) DEFAULT NULL COMMENT '姓名',
  password VARCHAR(64) DEFAULT NULL COMMENT '密码',
  salt VARCHAR(64) DEFAULT NULL COMMENT '盐',
  phone VARCHAR(32) DEFAULT NULL COMMENT '电话',
  email VARCHAR(64) DEFAULT NULL COMMENT '电子邮件',
  status VARCHAR(2) DEFAULT NULL COMMENT '状态',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  update_time DATETIME DEFAULT NULL COMMENT '修改时间',
  login_time DATETIME DEFAULT NULL COMMENT '最近一次登录时间',
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户信息表';

--
-- Definition for table sys_user_menu
--
DROP TABLE IF EXISTS sys_user_menu;
CREATE TABLE sys_user_menu (
  user_id INT(11) NOT NULL COMMENT '用户ID',
  menu_id VARCHAR(20) NOT NULL COMMENT '菜单ID',
  create_user VARCHAR(32) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (user_id, menu_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户菜单表';

--
-- Definition for table sys_user_role
--
DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role (
  user_id INT(11) NOT NULL DEFAULT 0 COMMENT '用户id',
  role_id VARCHAR(20) NOT NULL DEFAULT '' COMMENT '角色id',
  creator INT(11) DEFAULT NULL COMMENT '创建人',
  create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (user_id, role_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户角色表';

--
-- Definition for table test
--
DROP TABLE IF EXISTS test;
CREATE TABLE test (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '流水号',
  name VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '测试表';

-- 
-- Dumping data for table sys_menu_info
--
INSERT INTO sys_menu_info VALUES
('000', '首页', '000', '/backStage/home', 'icon-dashboard', '1', NULL),
('100', '系统管理', '100', '', 'icon-screenshot', '1', NULL),
('100100', '用户管理', '100100', '/backStage/sys/user/list', NULL, '1', NULL);

-- 
-- Dumping data for table sys_role_info
--

-- Table jsuweb.sys_role_info does not contain any data (it is empty)

-- 
-- Dumping data for table sys_seq
--

-- Table jsuweb.sys_seq does not contain any data (it is empty)

-- 
-- Dumping data for table sys_user_info
--
INSERT INTO sys_user_info VALUES
(1, 'system', '系统管理员', '46mQqhbPwrQemicSNP4VNm3w==', '46aNz2yXqTceulVt', '13311111111', 'sujian@qq.com', '1', NULL, NULL, '2017-04-05 14:38:10'),
(2, 'sujian', '苏测试', '46mQqhbPwrQemicSNP4VNm3w==', '46aNz2yXqTceulVt', '13311112111', 'sujian@qq.com', '1', NULL, NULL, '2017-04-01 18:07:46');

-- 
-- Dumping data for table sys_user_menu
--
INSERT INTO sys_user_menu VALUES
(1, '000', NULL, NULL),
(1, '100', NULL, NULL),
(1, '100100', NULL, NULL),
(1, '100200', NULL, NULL);

-- 
-- Dumping data for table sys_user_role
--

-- Table jsuweb.sys_user_role does not contain any data (it is empty)

-- 
-- Dumping data for table test
--

-- Table jsuweb.test does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;